In [1]:
import numpy as np
import pandas as pd


In [2]:
#  Import and read the charity_data.csv.
credit_score_df = pd.read_csv("credit_score_new.csv")
credit_score_df.head()

Unnamed: 0      ID Customer_ID  Month  Annual_Income  \
0           0  0x1602   CUS_0xd40      1       19114.12   
1           1  0x1608   CUS_0xd40      7       19114.12   
2           2  0x1626  CUS_0xb891      1       30689.89   
3           3  0x1627  CUS_0xb891      2       30689.89   
4           4  0x1628  CUS_0xb891      3       30689.89   

   Monthly_Inhand_Salary  Num_Bank_Accounts  Num_Credit_Card  Interest_Rate  \
0            1824.843333                  3                4              3   
1            1824.843333                  3                4              3   
2            2612.490833                  2                5              4   
3            2612.490833                  2                5              4   
4            2612.490833                  2                5              4   

   Num_of_Loan  ... Credit_History_Age  Payment_of_Min_Amount  \
0          4.0  ...               22.1                     No   
1          4.0  ...               22.7                     No   
2          1.0  ...               17.3                     No   
3          1.0  ...               17.4                     No   
4          1.0  ...               17.5                     NM   

   Total_EMI_per_month  Amount_invested_monthly  \
0            49.574949                80.415295   
1            49.574949               178.344067   
2            16.415452                81.228859   
3            16.415452               124.881820   
4            16.415452                83.406509   

                  Payment_Behaviour  Monthly_Balance  Credit_Score  \
0   High_spent_Small_value_payments       312.494089          Good   
1    Low_spent_Small_value_payments       244.565317          Good   
2    Low_spent_Large_value_payments       433.604773      Standard   
3    Low_spent_Small_value_payments       409.951812      Standard   
4  High_spent_Medium_value_payments       411.427123      Standard   

            Name   Age    Occupation  
0  Aaron Maashoh  23.0     Scientist  
1  Aaron Maashoh  23.0     Scientist  
2         Jasond  55.0  Entrepreneur  
3         Jasond  55.0  Entrepreneur  
4         Jasond  55.0  Entrepreneur  

[5 rows x 26 columns]

In [3]:
credit_score_df = credit_score_df.drop(['Type_of_Loan','Unnamed: 0','Annual_Income','Customer_ID','ID','Name','Occupation','Amount_invested_monthly'],axis = 1)
credit_score_df.head()

Month  Monthly_Inhand_Salary  Num_Bank_Accounts  Num_Credit_Card  \
0      1            1824.843333                  3                4   
1      7            1824.843333                  3                4   
2      1            2612.490833                  2                5   
3      2            2612.490833                  2                5   
4      3            2612.490833                  2                5   

   Interest_Rate  Num_of_Loan  Delay_from_due_date  Num_of_Delayed_Payment  \
0              3          4.0                    3                     7.0   
1              3          4.0                    3                     8.0   
2              4          1.0                    0                     6.0   
3              4          1.0                    5                     3.0   
4              4          1.0                    3                     9.0   

   Num_Credit_Inquiries  Outstanding_Debt  Credit_Utilization_Ratio  \
0                   4.0            809.98                 26.822620   
1                   4.0            809.98                 22.537593   
2                   4.0            632.46                 26.544229   
3                   4.0            632.46                 35.279982   
4                   4.0            632.46                 32.301163   

   Credit_History_Age Payment_of_Min_Amount  Total_EMI_per_month  \
0                22.1                    No            49.574949   
1                22.7                    No            49.574949   
2                17.3                    No            16.415452   
3                17.4                    No            16.415452   
4                17.5                    NM            16.415452   

                  Payment_Behaviour  Monthly_Balance Credit_Score   Age  
0   High_spent_Small_value_payments       312.494089         Good  23.0  
1    Low_spent_Small_value_payments       244.565317         Good  23.0  
2    Low_spent_Large_value_payments       433.604773     Standard  55.0  
3    Low_spent_Small_value_payments       409.951812     Standard  55.0  
4  High_spent_Medium_value_payments       411.427123     Standard  55.0

In [4]:
# Create our features
X = credit_score_df.copy()
X = X.drop("Credit_Score", axis=1)
X = pd.get_dummies(X)



# Create our target
y = pd.DataFrame(credit_score_df,columns = ["Credit_Score"])


In [5]:
X.describe()

Month  Monthly_Inhand_Salary  Num_Bank_Accounts  \
count  48553.000000           48553.000000       48553.000000   
mean       4.488785            4155.531542          16.574609   
std        2.293813            3173.526932         114.427362   
min        1.000000             319.556250          -1.000000   
25%        2.000000            1617.160833           3.000000   
50%        4.000000            3044.806667           6.000000   
75%        6.000000            5913.505000           7.000000   
max        8.000000           15167.180000        1794.000000   

       Num_Credit_Card  Interest_Rate   Num_of_Loan  Delay_from_due_date  \
count     48553.000000   48553.000000  48553.000000         48553.000000   
mean         22.687249      74.505654      2.893395            20.970403   
std         128.814423     476.489303     61.174505            14.770478   
min           0.000000       1.000000   -100.000000            -5.000000   
25%           4.000000       8.000000      1.000000            10.000000   
50%           6.000000      13.000000      3.000000            18.000000   
75%           7.000000      20.000000      5.000000            28.000000   
max        1499.000000    5797.000000   1485.000000            67.000000   

       Num_of_Delayed_Payment  Num_Credit_Inquiries  Outstanding_Debt  ...  \
count            48553.000000          48553.000000      48553.000000  ...   
mean                30.903302             27.340597       1417.608559  ...   
std                225.148420            191.366958       1147.908145  ...   
min                 -3.000000              0.000000          0.770000  ...   
25%                  9.000000              3.000000        566.340000  ...   
50%                 14.000000              6.000000       1160.830000  ...   
75%                 18.000000              9.000000       1924.320000  ...   
max               4360.000000           2592.000000       4998.070000  ...   

                Age  Payment_of_Min_Amount_NM  Payment_of_Min_Amount_No  \
count  48553.000000              48553.000000              48553.000000   
mean      33.573353                  0.119272                  0.357218   
std       10.813373                  0.324111                  0.479185   
min       15.000000                  0.000000                  0.000000   
25%       25.000000                  0.000000                  0.000000   
50%       33.000000                  0.000000                  0.000000   
75%       41.000000                  0.000000                  1.000000   
max       95.000000                  1.000000                  1.000000   

       Payment_of_Min_Amount_Yes  \
count               48553.000000   
mean                    0.523510   
std                     0.499452   
min                     0.000000   
25%                     0.000000   
50%                     1.000000   
75%                     1.000000   
max                     1.000000   

       Payment_Behaviour_High_spent_Large_value_payments  \
count                                       48553.000000   
mean                                            0.150866   
std                                             0.357922   
min                                             0.000000   
25%                                             0.000000   
50%                                             0.000000   
75%                                             0.000000   
max                                             1.000000   

       Payment_Behaviour_High_spent_Medium_value_payments  \
count                                       48553.000000    
mean                                            0.190534    
std                                             0.392726    
min                                             0.000000    
25%                                             0.000000    
50%                                             0.000000    
75%                                             0.000000    
max       

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [8]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)


In [9]:
from pathlib import Path
from collections import Counter

In [10]:
Counter(y_resampled)

Counter({'Credit_Score': 1})

In [11]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs',random_state=1)
model.fit(X_resampled, y_resampled)


/Users/liuyidi/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/liuyidi/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=1)

In [12]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)


0.3333333333333333

In [13]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[2117,    0,    0],
       [3594,    0,    0],
       [6428,    0,    0]])

In [14]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))


                   pre       rec       spe        f1       geo       iba       sup

       Good       0.17      1.00      0.00      0.30      0.00      0.00      2117
       Poor       0.00      0.00      1.00      0.00      0.00      0.00      3594
   Standard       0.00      0.00      1.00      0.00      0.00      0.00      6428

avg / total       0.03      0.17      0.83      0.05      0.00      0.00     12139



/Users/liuyidi/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [15]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy='auto').fit_resample(
    X_train, y_train
)
Counter(y_resampled)

Counter({'Credit_Score': 1})

In [16]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

/Users/liuyidi/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=1)

In [17]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)


0.3333333333333333

In [18]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[2117,    0,    0],
       [3594,    0,    0],
       [6428,    0,    0]])

In [19]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))


                   pre       rec       spe        f1       geo       iba       sup

       Good       0.17      1.00      0.00      0.30      0.00      0.00      2117
       Poor       0.00      0.00      1.00      0.00      0.00      0.00      3594
   Standard       0.00      0.00      1.00      0.00      0.00      0.00      6428

avg / total       0.03      0.17      0.83      0.05      0.00      0.00     12139



/Users/liuyidi/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
# Resample the data using the ClusterCentroids resampler
# Warning: This is a large dataset, and this step may take some time to complete
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)
Counter(y_resampled)


/Users/liuyidi/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/imblearn/under_sampling/_prototype_generation/_cluster_centroids.py:178: ConvergenceWarning: Number of distinct clusters (6517) found smaller than n_clusters (6519). Possibly due to duplicate points in X.
  self.estimator_.fit(_safe_indexing(X, target_class_indices))
/Users/liuyidi/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/imblearn/under_sampling/_prototype_generation/_cluster_centroids.py:178: ConvergenceWarning: Number of distinct clusters (6399) found smaller than n_clusters (6519). Possibly due to duplicate points in X.
  self.estimator_.fit(_safe_indexing(X, target_class_indices))


Counter({'Credit_Score': 1})

In [21]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

/Users/liuyidi/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/liuyidi/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=1)

In [22]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)


0.3333333333333333

In [23]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[2117,    0,    0],
       [3594,    0,    0],
       [6428,    0,    0]])

In [24]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

/Users/liuyidi/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                   pre       rec       spe        f1       geo       iba       sup

       Good       0.17      1.00      0.00      0.30      0.00      0.00      2117
       Poor       0.00      0.00      1.00      0.00      0.00      0.00      3594
   Standard       0.00      0.00      1.00      0.00      0.00      0.00      6428

avg / total       0.03      0.17      0.83      0.05      0.00      0.00     12139



In [25]:
# Resample the training data with SMOTEENN
# Warning: This is a large dataset, and this step may take some time to complete
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=1)
X_resampled, y_resampled = smote_enn.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({'Credit_Score': 1})

In [26]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

/Users/liuyidi/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/liuyidi/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=1)

In [27]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.560312257766894

In [28]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)


array([[1911,  192,   14],
       [ 809, 2778,    7],
       [4315, 2079,   34]])

In [29]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced

print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

       Good       0.27      0.90      0.49      0.42      0.66      0.46      2117
       Poor       0.55      0.77      0.73      0.64      0.75      0.57      3594
   Standard       0.62      0.01      1.00      0.01      0.07      0.00      6428

avg / total       0.54      0.39      0.83      0.27      0.38      0.25     12139

